// This file was auto-generated by ML.NET Model Builder. 

using System;
using Projectml_netML.Model;

namespace Projectml_netML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Title = @"Miss Jerry",
                Actors = @"Blanche Bayliss, William Courtenay, Chauncey Depew",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Genre with predicted Genre from sample data...\n\n");
            Console.WriteLine($"Title: {sampleData.Title}");
            Console.WriteLine($"Actors: {sampleData.Actors}");
            Console.WriteLine($"\n\nPredicted Genre value {predictionResult.Prediction} \nPredicted Genre scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
